name: Python Tests
on:
  pull_request:
    paths:
      - 'python/movie-review-analysis/**'
  workflow_dispatch:

jobs:

    python-exe-check:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.13'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r python/movie-review-analysis/requirements.txt
    
        - name: Run Python executable check
          run: |
            cd python/movie-review-analysis
            python -m py_compile chat_with_llm.py

    run-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.13'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r python/movie-review-analysis/requirements.txt
    
        - name: Run tests
          run: |
            pip install pytest pytest-cov
            cd python/movie-review-analysis
            pytest --cov=chat_with_llm --cov-report=xml
        - name: Upload coverage report
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report
            path: python/movie-review-analysis/.coverage

    check-coverage:
        runs-on: ubuntu-latest
        needs: run-tests
        steps:
        - name: Download coverage report
          uses: actions/download-artifact@v4
          with:
            name: coverage-report
            path: python/movie-review-analysis

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.13'

        - name: Install coverage tool
          run: |
            python -m pip install --upgrade pip
            pip install coverage

        - name: Check coverage
          run: |
            cd python/movie-review-analysis
            coverage xml -i --rcfile=.coveragerc
            coverage report --fail-under=30
