name: Python Tests
on:
  pull_request:
    paths:
      - 'python/chat-cli/**'
  workflow_dispatch:

jobs:

    py-compile:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.13'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r python/chat-cli/requirements.txt
    
        - name: Run Python executable check
          run: |
            cd python/chat-cli
            python -m py_compile chat_with_llm.py

    flake8:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.13'
    
        - name: Install flake8
          run: |
            python -m pip install --upgrade pip
            pip install flake8==7.2.0
    
        - name: Run flake8
          run: |
            cd python/chat-cli
            flake8 --max-line-length=120 --ignore=E501,E203 chat_with_llm.py

 
    pytest:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.13'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r python/chat-cli/requirements.txt
    
        - name: Run tests
          run: |
            pip install pytest pytest-cov
            cd python/chat-cli
            pytest --cov=chat_with_llm --cov-report=xml
